name: socket_mobile
description: Socket Mobile Capture SDK
version: 1.0.0
homepage: https://github.com/jonathantribouharet/flutter_socket_mobile

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  equatable: any
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      android:
        package: co.eivo.socket_mobile
        pluginClass: SocketMobilePlugin
      ios:
        pluginClass: SocketMobilePlugin
